import assert from 'node:assert/strict';
import { GET, POST, PUT } from '../app/api/inspections/route';
import { setTestUser } from './api-fixture';
import {blankMeta,blankEntry} from '../lib/model';
const id=crypto.randomUUID(),mutationId=crypto.randomUUID();
const doc={schemaVersion:1,checklistVersion:'test',meta:{...blankMeta(),vin:'7PD2EAAB0VN000001',deliveryDate:'2026-09-24',location:'Sample'},entries:{paint:blankEntry()},overallNotes:'',deliveryDecision:'undecided'};
const req=(method:string,payload?:unknown)=>new Request('https://app.test/api/inspections',{method,headers:{'content-type':'application/json','x-inspection-client':'1'},body:payload?JSON.stringify(payload):undefined});
let response=await POST(req('POST',{id,mutationId,document:doc}));assert.equal(response.status,201);
response=await POST(req('POST',{id,mutationId,document:doc}));assert.equal(response.status,200,'create retry must be idempotent');
const current=await response.json() as {revision:number};assert.equal(current.revision,1);
response=await PUT(req('PUT',{id,revision:1,mutationId:crypto.randomUUID(),document:{...doc,overallNotes:'First device'}}));assert.equal(response.status,200);
response=await PUT(req('PUT',{id,revision:1,mutationId:crypto.randomUUID(),document:{...doc,overallNotes:'Stale second device'}}));assert.equal(response.status,409,'stale edits must not overwrite');
response=await GET(new Request('https://app.test/api/inspections?id='+id+'&last4=0001'));assert.equal((await response.json() as {document:{overallNotes:string}}).document.overallNotes,'First device');
setTestUser('owner-b');response=await GET(new Request('https://app.test/api/inspections?id='+id+'&last4=0001'));assert.equal(response.status,404);
response=await GET(new Request('https://app.test/api/inspections'));assert.deepEqual((await response.json() as {inspections:unknown[]}).inspections,[]);
response=await PUT(req('PUT',{id,revision:2,mutationId:crypto.randomUUID(),document:doc}));assert.equal(response.status,404);
setTestUser(null);response=await GET(new Request('https://app.test/api/inspections'));assert.equal(response.status,401);assert.match(response.headers.get('cache-control')||'',/no-store/);
setTestUser('owner-a');response=await POST(new Request('https://app.test/api/inspections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),mutationId,document:doc})}));assert.equal(response.status,400);
console.log('PASS: SQLite-backed API creation, idempotent retries, optimistic conflicts, owner isolation for read/list/write, anonymous rejection, no-store, CSRF header enforcement.');
