import assert from 'node:assert/strict';
import { deliverySections, followupSections, currentSections, recordSections, previousSections, makeDocument, inspectionSummary } from '../lib/inspection-plan';
import { blankEntry, blankMeta, counts, documentSchema, mergeDocuments, entryWithStatus } from '../lib/model';
import legacy from '../lib/checklist.json';

const pickupIds = deliverySections.flatMap(section => section.items.map(item => item.id));
const followupIds = followupSections.flatMap(section => section.items.map(item => item.id));
assert.equal(pickupIds.length, 20); assert.equal(deliverySections.length, 4);
assert.equal(followupIds.length, 10); assert.equal(new Set([...pickupIds, ...followupIds]).size, 30);
assert.ok(followupIds.includes('follow-drive') && followupIds.includes('follow-charging') && followupIds.includes('follow-storage'));
assert.ok(pickupIds.every(id => id.startsWith('quick-')));
const fresh = makeDocument({ ...blankMeta(), vin: '7PD2EAAB0VN000001', deliveryDate: '2026-09-24', location: 'Sample center' });
assert.equal(documentSchema.safeParse(fresh).success, true);
assert.equal(Object.keys(fresh.entries).length, 30);
assert.equal(previousSections(fresh).length, 0);
assert.deepEqual(inspectionSummary(fresh), { total: 20, completed: 0, issues: 0 });
for (const id of pickupIds) fresh.entries[id].status = 1;
assert.equal(inspectionSummary(fresh).completed, 20);
assert.equal(counts(fresh, followupSections).pending, 10, 'Follow-up must not block pickup completion or be auto-passed');
assert.equal(counts(fresh, currentSections).reviewed, 20);

const old = { ...makeDocument(fresh.meta), checklistVersion: 'r2-pickup-2026-09-v1', entries: Object.fromEntries(legacy.sections.flatMap(section => section.items).map(item => [item.id, blankEntry()])) };
old.entries.paint = { status: 2, note: 'Earlier paint concern', action: 'Original ticket retained', resolved: false };
old.entries['vin-match'].status = 1;
old.entries['phone-key'].status = 'later';
old.entries['future-saved-check'] = { status: 0, note: 'Keep unknown earlier notes', action: '', resolved: false };
const original = JSON.stringify(old);
assert.deepEqual(inspectionSummary(old), { total: 20, completed: 0, issues: 1 });
const oldRows = previousSections(old).flatMap(section => section.items);
assert.equal(oldRows.length, 4);
assert.ok(oldRows.some(item => item.id === 'future-saved-check'));
assert.equal(counts(old, recordSections(old)).open, 1);
assert.equal(JSON.stringify(old), original, 'Rendering the new plan must not mutate existing data');
assert.equal(old.entries['quick-paint'], undefined, 'An earlier paint observation cannot pass a grouped quick task');
const mine = structuredClone(old), theirs = structuredClone(old);
mine.entries['quick-panels'] = { ...blankEntry(), status: 1 };
theirs.entries.glass = { ...blankEntry(), status: 3, note: 'Other device concern' };
const merged = mergeDocuments(old, mine, theirs);
assert.equal(merged.conflicts.length, 0);
assert.equal(merged.merged.entries['quick-panels'].status, 1);
assert.equal(merged.merged.entries.glass.status, 3);
assert.equal(merged.merged.entries.paint.action, 'Original ticket retained');
assert.equal(documentSchema.safeParse(merged.merged).success, true);
const allIds = recordSections(merged.merged).flatMap(section => section.items.map(item => item.id));
assert.equal(new Set(allIds).size, allIds.length, 'Reports must not duplicate an entry');
const escalated=entryWithStatus({...blankEntry(),status:2,resolved:true},3);
assert.equal(escalated.resolved,false,'A changed severity must reopen a resolved issue');
assert.equal(entryWithStatus({...blankEntry(),status:2,resolved:true},2).resolved,true);
console.log('PASS: 20 parked pickup checks; 10 separate follow-ups; truthful progress; old/unknown entries and cross-device edits preserved.');
