'use client';
import { newId } from '@/lib/id';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCheck, CheckCircle2, ChevronDown, ClipboardCheck, CloudCheck, Download, FileDown, Flag, KeyRound, ListChecks, LoaderCircle, LockKeyhole, MessageSquare, Minus, Plus, Save, Settings2, ShieldCheck, TriangleAlert, X, Clock3, RefreshCw, ExternalLink } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster, toast } from 'sonner';
import { blankEntry, blankMeta, counts, displayDate, isIssue, isReviewed, labels, nextStatus, entryWithStatus, documentSchema, type Entry, type Inspection, type InspectionSummary, type SavedInspection, type Status, type VehicleMeta, type CheckItem } from '@/lib/model';
import { configuration, configurationSource } from '@/lib/configuration';
import { ConfigurationImport } from '@/components/configuration-import';
import { InspectionWalkthrough } from '@/components/inspection-walkthrough';
import { InspectionTime } from '@/components/inspection-time';
import { minutesLabel, sectionMinutes } from '@/lib/inspection-time';
import { deliverySections, followupSections, currentSections, recordSections, previousSections, makeDocument, pickupSections, accessoryNamesFor, type InspectionPhase } from '@/lib/inspection-plan';
import { api, useInspection } from '@/lib/use-inspection';
const StatusIcon=({status,size=21}:{status:Status;size?:number})=>status===1?<Check size={size} strokeWidth={2.4}/>:status===2?<Minus size={size} strokeWidth={2.6}/>:status===3?<X size={size} strokeWidth={2.4}/>:status==='na'?<Minus size={size}/>:status==='later'?<Clock3 size={size}/>:<span aria-hidden="true"/>;
function SourceNotes(){return <details className="sources"><summary>Checklist sources & reporting guidance</summary><p className="source-small">The short pickup list follows your uploaded Super EV LOG delivery-day checklist. It covers a parked inspection; driving, longer setup and follow-up checks come after acceptance.</p><a href="https://www.youtube.com/watch?v=jAC7ajGA_S4" target="_blank" rel="noreferrer">Super EV LOG · R2 delivery video</a><a href="https://rivian.com/experience/service" target="_blank" rel="noreferrer">Rivian · report issues and request service</a><a href={configurationSource} target="_blank" rel="noreferrer">Rivian R2 configurator</a><p className="source-small">Confirm your cosmetic-reporting deadline with the delivery specialist in writing and record it under Handover. “First week” is a follow-up plan; the applicable reporting instructions come from your delivery team. Report concerns as you find them.</p><p className="source-small">Official R2 artwork © Rivian. Exterior rotation uses configurator images; open-compartment and interior views are cropped from your supplied configurator screenshots. Gold dots in those screenshots are Rivian’s original feature markers, not inspection results. Highlights are an approximate area guide, not a diagnostic model. Independent personal inspection aid. Keep agreed repairs in Rivian’s written delivery or service record as well.</p></details>}
function Picker({id,label,value,options,onChange,placeholder='Select an option',allowCustom=false}:{id:string;label:string;value:string;options:string[];onChange:(v:string)=>void;placeholder?:string;allowCustom?:boolean}){
 const [customSelected,setCustom]=useState(!!value&&!options.includes(value));
 const custom=!options.includes(value)&&(!!value||customSelected);
 return <div className="field"><label htmlFor={id}>{label}</label><Select value={custom?'__custom':value||undefined} onValueChange={v=>{if(v==='__custom'){setCustom(true);onChange('')}else{setCustom(false);onChange(v)}}}><SelectTrigger id={id} className="select-control"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent position="popper">{options.map(option=><SelectItem key={option} value={option}>{option}</SelectItem>)}{allowCustom&&<SelectItem value="__custom">Other / enter from order</SelectItem>}</SelectContent></Select>{custom&&<input aria-label={label+' from order'} value={value} onChange={e=>onChange(e.target.value)} placeholder="Enter exactly as ordered" maxLength={250}/>}</div>
}
function MetaForm({initial,onSubmit,busy,editing=false,onCancel}:{initial:VehicleMeta;onSubmit:(m:VehicleMeta,original?:VehicleMeta)=>void;busy:boolean;editing?:boolean;onCancel?:()=>void}){
 const [meta,setMeta]=useState(initial),[error,setError]=useState('');const original=useRef(initial);
 const change=(field:keyof VehicleMeta,value:string)=>setMeta(m=>({...m,[field]:value}));
 const field=(id:keyof VehicleMeta,label:string,opts:{wide?:boolean;type?:string;placeholder?:string;required?:boolean}={})=><div className={'field '+(opts.wide?'wide':'')}><label htmlFor={'meta-'+id}>{label}{opts.required?' *':''}</label><input id={'meta-'+id} type={opts.type||'text'} value={meta[id]} onInput={e=>change(id,e.currentTarget.value)} onChange={e=>change(id,e.target.value)} placeholder={opts.placeholder} required={opts.required} maxLength={250}/></div>;
 return <form onSubmit={e=>{e.preventDefault();const result=documentSchema.shape.meta.safeParse({...meta,vin:meta.vin.toUpperCase().replace(/\s/g,'')});if(!result.success){setError(result.error.issues[0].message);return;}if(Object.keys(accessoryNamesFor(result.data.accessories)).length>100){setError('Use no more than 100 accessory items.');return;}setError('');onSubmit(result.data,original.current)}}>
 <ConfigurationImport current={meta} editing={editing} onApply={value=>{setMeta(value);setError('')}}/>
 <div className="form-section first">01 / Vehicle & delivery</div><div className="field-grid">
 <div className="field wide"><label htmlFor="vin">Full VIN *</label><input id="vin" className="vin-input" autoCapitalize="characters" autoComplete="off" spellCheck={false} value={meta.vin} maxLength={17} minLength={17} pattern="[A-HJ-NPR-Z0-9]{17}" required disabled={editing} onChange={e=>change('vin',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="17-character vehicle identification number"/><p className="field-help">{editing?'Your VIN identifies this inspection.':'Use the full VIN from your purchase agreement. Reopen with its last four characters.'}</p></div>
 {field('deliveryDate','Delivery date',{type:'date',required:true})}{field('deliveryTime','Appointment time',{type:'time'})}{field('location','Delivery location',{wide:true,required:true,placeholder:'Service center or delivery address'})}{field('inspector','Inspector',{placeholder:'Your name (optional)'})}{field('specialist','Delivery specialist',{placeholder:'Name (optional)'})}</div>
 <div className="form-section">02 / Your configuration</div><div className="field-grid">
 <Picker id="trim" label="R2 trim" value={meta.trim} options={configuration.trims} onChange={v=>change('trim',v)} allowCustom/>
 <Picker id="package" label="Package" value={meta.package} options={configuration.packages} onChange={v=>change('package',v)} allowCustom/>
 <Picker id="paint" label="Exterior paint" value={meta.paint} options={configuration.paints} onChange={v=>change('paint',v)} allowCustom/>
 <Picker id="interior" label="Interior" value={meta.interior} options={configuration.interiors} onChange={v=>change('interior',v)} allowCustom/>
 <div className="field wide"><Picker id="wheels" label="Wheels & tires" value={meta.wheels} options={configuration.wheels} onChange={v=>change('wheels',v)} allowCustom/></div>
 <div className="field wide"><label htmlFor="accessories">Options & accessories</label><textarea id="accessories" value={meta.accessories} maxLength={2000} onChange={e=>change('accessories',e.target.value)} placeholder="Tow package, mats, spare, chargers, or anything else on your order" rows={2}/><p className="field-help">Put each item on a separate line, or separate items with commas. Each becomes its own pickup check.</p></div></div>
 <p className="source-small">Confirm selections against your final order. <a href={configurationSource} target="_blank" rel="noreferrer" style={{textDecoration:'underline'}}>Open Rivian’s configurator ↗</a></p>
 <div className="form-section">03 / At handoff <span className="muted">· optional now</span></div><div className="field-grid">{field('odometer','Odometer',{placeholder:'Miles'})}{field('battery','Battery level',{placeholder:'% at handoff'})}{field('software','Software version',{wide:true,placeholder:'From Settings → About'})}</div>
 {error&&<div className="error-box" role="alert">{error}</div>}
 <div className="form-actions flex gap-2">{onCancel&&<button type="button" className="btn" onClick={onCancel}>Cancel</button>}<button className="btn primary" disabled={busy} type="submit">{busy?<LoaderCircle size={18} className="compact-spinner"/>:<ClipboardCheck size={18}/>} {editing?'Save vehicle details':'Create inspection'}</button></div>
 </form>
}
function CheckRow({item,entry,change,expanded:forcedExpanded=false}:{item:CheckItem;entry:Entry;change:(entry:Entry)=>void;expanded?:boolean}){
 const [expanded,setExpanded]=useState(forcedExpanded);
 const issue=isIssue(entry);
 const setStatus=(status:Status)=>change(entryWithStatus(entry,status));
 return <article className={'check-item '+(issue?'is-issue ':'')+(entry.status===3?'is-major':'')} id={'check-'+item.id}>
 <div className="item-main"><button className={'cycle-button status-'+entry.status} onClick={()=>setStatus(nextStatus(entry.status))} aria-label={item.title+': '+labels[String(entry.status)]+'. Tap for '+labels[String(nextStatus(entry.status))]} title="Tap again to cycle status"><StatusIcon status={entry.status}/></button>
 <div className="item-text"><h3 className="item-title">{item.title}</h3><p className="item-detail">{item.detail}</p><div className="item-tags"><span className={'pill status-'+entry.status}>{labels[String(entry.status)]}</span>{entry.resolved&&issue&&<span className="pill status-1"><CheckCheck size={12}/>Resolved</span>}{item.conditional&&<span className="pill">If equipped</span>}</div><button className="item-expand" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}><MessageSquare size={14}/>{entry.note||entry.action?'View notes':'Notes & status'}<ChevronDown size={13} style={{transform:expanded?'rotate(180deg)':'none'}}/></button></div></div>
 {expanded&&<div className="item-editor"><div className="status-options" aria-label={'Set status for '+item.title}>{([0,1,2,3,'na','later'] as Status[]).map(status=><button key={status} type="button" className={'status-option '+(entry.status===status?'selected':'')} aria-pressed={entry.status===status} onClick={()=>setStatus(status)}>{labels[String(status)]}</button>)}</div>
 <div className="field"><label htmlFor={'note-'+item.id}>Observations & photo references</label><textarea id={'note-'+item.id} maxLength={4000} value={entry.note} onChange={e=>change({...entry,note:e.target.value})} placeholder="Location of issue, what you noticed, photo number…"/></div>
 {issue&&<><div className="field"><label htmlFor={'action-'+item.id}>Agreed action / service ticket</label><textarea id={'action-'+item.id} maxLength={2000} rows={2} value={entry.action} onChange={e=>change({...entry,action:e.target.value})} placeholder="What will be done, by whom, and when?"/></div><label className="resolve-check"><Checkbox checked={entry.resolved} onCheckedChange={v=>change({...entry,resolved:v===true})}/>Issue resolved / repair verified</label></>}
 </div>}
 </article>
}
export default function PickupApp({signedIn,userKey,signInPath}:{signedIn:boolean;userKey:string;signInPath:string}){
 const manager=useInspection(userKey);const doc=manager.document;
 const [phase,setPhase]=useState<InspectionPhase>('pickup');
 const pickup=doc?pickupSections(doc):deliverySections;
 const sections=phase==='pickup'?pickup:followupSections;
 const documentSections=doc?recordSections(doc):currentSections;
 const allItems=documentSections.flatMap(section=>section.items.map(item=>({...item,sectionTitle:section.title})));
 const previous=doc?previousSections(doc):[];
 const [summaries,setSummaries]=useState<InspectionSummary[]>([]),[loading,setLoading]=useState(signedIn),[homeTab,setHomeTab]=useState('open'),[homeError,setHomeError]=useState(''),[busy,setBusy]=useState(false),[last4,setLast4]=useState('');
 const [sectionIndex,setSectionIndex]=useState(0),[view,setView]=useState('checklist'),[editing,setEditing]=useState(false),[showExport,setShowExport]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[pdfError,setPdfError]=useState(''),[pdfUrl,setPdfUrl]=useState(''),[pdfName,setPdfName]=useState(''),[pdfFile,setPdfFile]=useState<File|null>(null),[pdfKind,setPdfKind]=useState('pickup'),[conflictChoices,setConflictChoices]=useState<Record<string,'mine'|'theirs'>>({});
 manager.setRefreshPaused(editing);
 const creation=useRef<{id:string;mutationId:string}|null>(null);
 const loadSummaries=async()=>{setLoading(true);try{const result=await api<{inspections:InspectionSummary[]}>('');setSummaries(result.inspections);if(!result.inspections.length)setHomeTab('new');setHomeError('')}catch(error){setHomeError((error as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{let cancelled=false;if(signedIn)api<{inspections:InspectionSummary[]}>('').then(result=>{if(cancelled)return;setSummaries(result.inspections);if(!result.inspections.length)setHomeTab('new');setHomeError('')}).catch(error=>{if(!cancelled)setHomeError(error.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[signedIn]);
 useEffect(()=>()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl)},[pdfUrl]);

 const attach=(saved:SavedInspection)=>{manager.attach(saved);setPhase('pickup');setSectionIndex(0);setView('checklist');history.replaceState(null,'','?inspection='+saved.id);window.scrollTo({top:0});};
 const create=async(meta:VehicleMeta)=>{setBusy(true);setHomeError('');creation.current??={id:newId(),mutationId:newId()};try{const record=await api<SavedInspection>('',{method:'POST',body:JSON.stringify({...creation.current,document:makeDocument(meta)})});creation.current=null;attach(record);toast.success('Your inspection is saved. You’re ready to begin.')}catch(error){setHomeError((error as Error).message)}finally{setBusy(false)}};
 const open=async(summary:InspectionSummary)=>{setBusy(true);setHomeError('');try{attach(await api<SavedInspection>('?id='+encodeURIComponent(summary.id)+'&last4='+encodeURIComponent(last4.toUpperCase())))}catch(error){setHomeError((error as Error).message)}finally{setBusy(false)}};
 const leave=async()=>{if(!doc)return;if(await manager.close()){history.replaceState(null,'','/');setHomeTab('open');void loadSummaries();setLast4('')}else toast.error('Save or resolve your pending changes before closing this inspection.');};
 const updateEntry=(id:string,entry:Entry)=>manager.edit(d=>({...d,entries:{...d.entries,[id]:entry}}));
 const changeSection=(index:number)=>{setSectionIndex(index);requestAnimationFrame(()=>document.getElementById(phase==='pickup'?'route-stop-'+sections[index].id:'workspace-start')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 const totals=doc?counts(doc,sections):null;
 const allTotals=doc?counts(doc,documentSections):null;
 const pickupTotals=doc?counts(doc,pickup):null;
 const followupTotals=doc?counts(doc,followupSections):null;
 const section=sections[sectionIndex]||sections[0];
 const accessoryChecks=section.items.filter(item=>item.id.startsWith('accessory-'));
 const saveLabel=manager.saveState==='saved'?'Saved to your account':manager.saveState==='saving'?'Saving…':manager.saveState==='conflict'?'Review conflicting edits':manager.saveState==='pending'?'Changes waiting to sync':manager.saveState==='offline'?'Offline · not synced':'Not synced · retry';
 const exportPdf=async()=>{
  if(!doc)return;setPdfBusy(true);setPdfError('');const snapshot=structuredClone(doc);const saved=manager.saveState==='saved';
  try{const {createInspectionPdf}=await import('@/lib/pdf-report');const reportSections=recordSections(snapshot);const blob=await createInspectionPdf(snapshot,pdfKind==='pickup'?pickupSections(snapshot):reportSections,{issuesOnly:pdfKind==='issues',saved,updatedAt:manager.record?.updatedAt||'',pickupOnly:pdfKind==='pickup',issueSections:reportSections});const name='R2-'+snapshot.meta.vin.slice(-4)+'-'+snapshot.meta.deliveryDate+'-'+(pdfKind==='issues'?'issues':pdfKind==='pickup'?'pickup':'complete-record')+'.pdf';if(pdfUrl)URL.revokeObjectURL(pdfUrl);setPdfUrl(URL.createObjectURL(blob));setPdfName(name);setPdfFile(new File([blob],name,{type:'application/pdf'}));}catch(error){setPdfError('The PDF could not be created. Your inspection is unchanged. '+(error as Error).message)}finally{setPdfBusy(false)}
 };
 const sharePdf=async()=>{if(!pdfFile)return;try{if(navigator.canShare?.({files:[pdfFile]})){await navigator.share({files:[pdfFile],title:'R2 pickup inspection'});}else{const a=document.createElement('a');a.href=pdfUrl;a.download=pdfName;a.click();}}catch(error){if((error as Error).name!=='AbortError')setPdfError('Sharing was unavailable. Use Download PDF or Open PDF below.')}};
 const resetExport=()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl);setPdfUrl('');setPdfFile(null);setPdfError('');setPdfKind(phase==='pickup'?'pickup':'full');setShowExport(true)};
 return <><Toaster position="top-center" richColors/><header className="topbar"><div className="topbar-inner"><button className="brand" onClick={()=>void leave()} aria-label="R2 Pickup Day home"><span className="brand-r2">R2</span><span className="brand-rule"/><span className="brand-name">PICKUP<br/>DAY</span></button><div className="top-actions"><div className="private-label"><LockKeyhole size={14}/><span>Private inspection</span></div>{signedIn&&<a className="account-link" href="/signout-with-chatgpt?return_to=/" target="_top" onClick={e=>{if(doc&&manager.saveState!=='saved'){e.preventDefault();toast.error('Save your changes before signing out.')}}}>Sign out</a>}</div></div></header>
 {!signedIn?<main className="shell"><section className="panel signin"><ShieldCheck size={31}/><p className="eyebrow" style={{marginTop:22}}>Rivian R2 · Delivery inspection</p><h1>A good start.<br/>Every detail checked.</h1><p>Inspect your R2, record what needs attention, and keep one checklist up to date across your devices.</p><div className="status-demo"><span className="pill status-1"><Check size={14}/>Good</span><span className="pill status-2"><Minus size={14}/>Minor issue</span><span className="pill status-3"><X size={14}/>Major issue</span></div><a className="btn primary full" href={signInPath} target="_top"><LockKeyhole size={17}/>Sign in with ChatGPT</a><p className="source-small" style={{margin:'14px 0 0'}}>Your account protects the full VIN and notes. The last four VIN characters help you reopen the right inspection.</p></section></main>:
 !doc?<main className="shell setup-shell"><div className="title-row"><div><p className="eyebrow" style={{margin:'0 0 10px'}}>Your delivery day, covered</p><h1>Ready for your R2.</h1><p>One inspection. Every detail. Saved as you go.</p></div><ClipboardCheck size={33} color="#52734b"/></div>
 <InspectionTime/>
 <Tabs className="page-tabs" value={homeTab} onValueChange={v=>{setHomeTab(v);setHomeError('')}}><TabsList><TabsTrigger value="open"><KeyRound size={16}/>Open inspection</TabsTrigger><TabsTrigger value="new"><Plus size={16}/>Set up vehicle</TabsTrigger></TabsList></Tabs>
 {homeError&&<div className="error-box" role="alert">{homeError}<button className="btn subtle" onClick={()=>void loadSummaries()}><RefreshCw size={15}/>Retry</button></div>}
 {loading?<div className="panel panel-body"><LoaderCircle className="compact-spinner" size={20}/> Loading your saved inspections…</div>:homeTab==='new'?<div className="setup-grid"><section className="panel"><div className="panel-heading"><ClipboardCheck size={22}/><h2>Your vehicle details</h2></div><div className="panel-body"><MetaForm initial={blankMeta()} onSubmit={create} busy={busy}/></div></section><aside className="setup-note"><p className="eyebrow">A walkaround that stays with you</p><h2>A quick check.<br/>A clear handover.</h2><div className="step"><span>1</span><p>Set up your VIN, delivery details, and configuration.</p></div><div className="step"><span>2</span><p>Complete 20 core parked checks plus your accessories in about 15–20 minutes.</p></div><div className="step"><span>3</span><p>Record concerns with your specialist. Continue driving and longer checks after delivery.</p></div><div className="notice"><ShieldCheck size={20}/><span>Your account keeps the inspection private on every device.</span></div></aside></div>:
 <section className="panel unlock-panel"><div className="panel-heading"><KeyRound size={22}/><h2>Pick up where you left off</h2></div><div className="panel-body"><p className="muted" style={{marginBottom:20}}>Enter the last four characters of your VIN.</p><div className="unlock-row"><div className="field"><label htmlFor="last4">VIN ending</label><input id="last4" className="unlock-input vin-input" inputMode="numeric" autoCapitalize="characters" autoComplete="off" spellCheck={false} maxLength={4} value={last4} placeholder="0000" onChange={e=>setLast4(e.target.value.toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,''))}/></div></div>
 {summaries.length===0?<div className="empty-state"><p>No saved inspections yet.</p><button className="btn primary" style={{marginTop:16}} onClick={()=>setHomeTab('new')}>Set up your R2</button></div>:last4.length===4?<div className="inspection-cards">{summaries.filter(s=>s.last4===last4).length? summaries.filter(s=>s.last4===last4).map(s=><div className="panel inspection-card" key={s.id}><div><h3 className="mono">R2 · {s.last4}</h3><p>{displayDate(s.deliveryDate)} · {s.location}</p><p style={{marginTop:7}}>{s.completed} of {s.total} pickup checks · {s.issues} open issues</p></div><button className="btn primary" disabled={busy} onClick={()=>void open(s)}>Open<ArrowRight size={15}/></button></div>):<p className="muted">No inspection matches that VIN ending in your account.</p>}</div>:<p className="source-small" style={{marginTop:18}}>{summaries.length} saved {summaries.length===1?'inspection':'inspections'} in your account.</p>}
 <p className="source-small" style={{marginTop:22}}>Use the same ChatGPT account on your iPhone, iPad, or computer. VIN lookup is available after sign-in.</p></div></section>}
 <SourceNotes/></main>:
 <main className="shell"><div className="vehicle-strip"><div><h1>Your R2 inspection</h1><div className="vehicle-meta"><span className="mono">VIN ··· {doc.meta.vin.slice(-4)}</span><span>{displayDate(doc.meta.deliveryDate)}</span><span>{doc.meta.paint||'Rivian R2'}</span></div><p className="small" style={{marginTop:4}}>{doc.meta.location}</p></div><button className="btn" onClick={()=>setEditing(true)}><Settings2 size={16}/><span>Vehicle</span></button></div>
 <div className="phase-picker" role="group" aria-label="Inspection stage"><button type="button" className={phase==='pickup'?'selected':''} aria-pressed={phase==='pickup'} onClick={()=>{setPhase('pickup');setSectionIndex(0);setView('checklist')}}><strong>At pickup</strong><span>{pickupTotals!.reviewed}/{pickupTotals!.total} · 15–20 min target</span></button><button type="button" className={phase==='followup'?'selected':''} aria-pressed={phase==='followup'} onClick={()=>{setPhase('followup');setSectionIndex(0);setView('checklist')}}><strong>After delivery</strong><span>{followupTotals!.reviewed}/10 · First week</span></button></div>
 <InspectionTime phase={phase} accessoryCount={pickupTotals!.total-20}/>
 <section className="progress-card" aria-label="Inspection progress"><div><div className="progress-main"><strong className="progress-number">{totals!.reviewed}<span style={{fontWeight:350,color:'#b8c9b5',fontSize:24}}> / {totals!.total}</span></strong><small>{phase==='pickup'?'pickup checks':'follow-up checks'}</small></div><Progress value={Math.round(totals!.reviewed/totals!.total*100)} aria-label="Checks reviewed"/><p className="progress-label">{totals!.pending>0?totals!.pending+' checks left to inspect':allTotals!.open>0?'Checks reviewed. See recorded concerns in Issues.':phase==='pickup'?'Pickup checks reviewed. Follow-up is separate.':'Follow-up checks reviewed.'}{totals!.na>0?' · '+totals!.na+' not applicable':''}</p></div><div className="progress-stats"><div className="stat"><strong>{totals!.good}</strong><span>Good</span></div><div className="stat minor"><strong>{totals!.minor}</strong><span>Minor</span></div><div className="stat major"><strong>{totals!.major}</strong><span>Major</span></div></div></section>
 {manager.message&&<div className={'notice '+(manager.saveState==='error'?'red':'amber')} role="status" style={{marginBottom:20}}><TriangleAlert size={18}/><span>{manager.message}{manager.localProtected?' Your changes are also preserved on this device.':''}</span></div>}
 <div id="workspace-start"><Tabs className="page-tabs" value={view} onValueChange={setView}><TabsList><TabsTrigger value="checklist"><ListChecks size={16}/>Checklist</TabsTrigger><TabsTrigger value="issues"><Flag size={16}/>Issues {allTotals!.open>0?'('+allTotals!.open+')':''}</TabsTrigger><TabsTrigger value="review"><ClipboardCheck size={16}/>Review</TabsTrigger></TabsList></Tabs></div>
 {view==='checklist'&&phase==='pickup'?<InspectionWalkthrough sections={pickup} doc={doc} renderCheck={item=><CheckRow item={item} entry={doc.entries[item.id]||blankEntry()} change={e=>updateEntry(item.id,e)}/>} onReview={()=>{setView('review');window.scrollTo({top:0,behavior:'smooth'})}}/>:view==='checklist'?<div className="workspace-grid"><nav className="section-nav" aria-label="Inspection sections"><h2>{phase==='pickup'?'At pickup':'After delivery'}</h2>{sections.map((s,i)=><button key={s.id} className={'section-btn '+(i===sectionIndex?'active':'')} aria-current={i===sectionIndex?'step':undefined} onClick={()=>changeSection(i)}><span className="section-no">{String(i+1).padStart(2,'0')}</span><span className="section-name">{s.title}</span><span className="section-count">{s.items.filter(item=>isReviewed(doc.entries[item.id])).length}/{s.items.length}</span></button>)}<div className="nav-footer">Good → Minor → Major → Unchecked.<br/>Tap the same box to cycle.</div></nav><section>
 <div className="mobile-section-select"><Select value={String(sectionIndex)} onValueChange={v=>changeSection(Number(v))}><SelectTrigger className="select-control" aria-label="Inspection section"><SelectValue/></SelectTrigger><SelectContent position="popper">{sections.map((s,i)=><SelectItem key={s.id} value={String(i)}>{String(i+1).padStart(2,'0')} · {s.title} ({s.items.filter(item=>isReviewed(doc.entries[item.id])).length}/{s.items.length})</SelectItem>)}</SelectContent></Select></div>
 <div className="section-heading"><div><span className="section-number">SECTION {String(sectionIndex+1).padStart(2,'0')} / {String(sections.length).padStart(2,'0')}</span><h2>{section.title}</h2><p>{section.subtitle}</p>{sectionMinutes[section.id]&&<p className="section-time"><Clock3 size={15}/>{minutesLabel(sectionMinutes[section.id])} target</p>}</div><span className="pill">{section.items.filter(i=>isReviewed(doc.entries[i.id])).length}/{section.items.length}</span></div>
 <div className="cycle-guide"><span><Check size={15} color="#24724c"/>1 tap · Good</span><span><Minus size={15} color="#956700"/>2 · Minor</span><span><X size={15} color="#a82e2c"/>3 · Major</span><span>4 · Reset</span></div>
 <div className="item-list">{section.items.map(item=>item.id.startsWith('accessory-')?null:item.id==='quick-equipment'&&accessoryChecks.length?<div className="accessory-group" key={item.id}><CheckRow item={item} entry={doc.entries[item.id]||blankEntry()} change={e=>updateEntry(item.id,e)}/><div className="accessory-checks"><p className="accessory-checks-heading">Ordered accessories · {accessoryChecks.filter(check=>isReviewed(doc.entries[check.id])).length}/{accessoryChecks.length} checked</p>{accessoryChecks.map(check=><CheckRow key={check.id} item={check} entry={doc.entries[check.id]||blankEntry()} change={e=>updateEntry(check.id,e)}/>)}</div></div>:<CheckRow key={item.id} item={item} entry={doc.entries[item.id]||blankEntry()} change={e=>updateEntry(item.id,e)}/>)}</div><div className="section-pager"><button className="btn" disabled={sectionIndex===0} onClick={()=>changeSection(sectionIndex-1)}><ArrowLeft size={16}/>Previous</button>{sectionIndex<sections.length-1?<button className="btn primary" onClick={()=>changeSection(sectionIndex+1)}>Next section<ArrowRight size={16}/></button>:<button className="btn primary" onClick={()=>{setView('review');window.scrollTo({top:0,behavior:'smooth'})}}>Review inspection<ArrowRight size={16}/></button>}</div>
 </section></div>:view==='issues'?<section><div className="section-heading"><div><h2>Recorded concerns</h2><p>Pickup, follow-up and earlier findings stay together. Keep the agreed action and service ticket with each concern.</p></div></div><div className="issue-summary"><span className="pill status-3">{allTotals!.major} major</span><span className="pill status-2">{allTotals!.minor} minor</span><span className="pill">{allTotals!.open} unresolved</span></div>
 {allTotals!.minor+allTotals!.major===0?<div className="panel empty-state"><CheckCircle2 size={34}/><h2>No issues recorded.</h2><p>Pickup: {pickupTotals!.reviewed}/{pickupTotals!.total} reviewed · After delivery: {followupTotals!.reviewed}/10 reviewed.</p></div>:<div className="issues-list">{allItems.filter(item=>isIssue(doc.entries[item.id])).sort((a,b)=>Number(doc.entries[b.id].status)-Number(doc.entries[a.id].status)).map(item=><div className="panel issue-panel" key={item.id}><p className="issue-reference">{item.sectionTitle}</p><CheckRow item={item} entry={doc.entries[item.id]} change={e=>updateEntry(item.id,e)} expanded/></div>)}</div>}</section>:
 <section><div className="section-heading"><div><h2>{phase==='pickup'?'Pickup review':'Follow-up review'}</h2><p>{phase==='pickup'?'Record the handover and your specialist’s instructions. Driving checks come after acceptance.':'Review concerns and submit service requests promptly.'}</p></div></div>{allTotals!.major>0&&<div className="notice red" style={{marginBottom:15}}><TriangleAlert size={20}/><span>{allTotals!.major} major {allTotals!.major===1?'issue':'issues'} recorded. Discuss any unresolved safety or drivability concern with the specialist before driving.</span></div>}{totals!.pending>0&&<div className="notice amber" style={{marginBottom:20}}><Clock3 size={19}/><span>{totals!.pending} {phase==='pickup'?'pickup':'follow-up'} checks are unchecked or not tested. They stay clearly marked in your report.</span></div>}
 <div className="panel panel-body"><h2 style={{fontSize:23,marginBottom:20}}>Section review</h2>{sections.map((s,i)=><button key={s.id} className="section-btn" onClick={()=>{setView('checklist');changeSection(i)}}><span className="section-no">{String(i+1).padStart(2,'0')}</span><span className="section-name">{s.title}</span><span className="section-count">{s.items.filter(item=>isReviewed(doc.entries[item.id])).length}/{s.items.length}</span><ArrowRight size={15}/></button>)}</div>
 <div className="panel panel-body decision-panel"><h2>Handoff notes</h2><p className="small" style={{marginBottom:7}}>Delivery outcome</p>
 <Select value={doc.deliveryDecision} onValueChange={v=>manager.edit(d=>({...d,deliveryDecision:v as Inspection['deliveryDecision']}))}><SelectTrigger className="select-control" style={{width:'100%',minHeight:48,marginBottom:20,fontSize:16}} aria-label="Delivery outcome"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="undecided">Not decided yet</SelectItem><SelectItem value="accepted">Accepted</SelectItem><SelectItem value="accepted-with-follow-up">Accepted with follow-up</SelectItem><SelectItem value="deferred">Delivery deferred</SelectItem></SelectContent></Select>
 <div className="field"><label htmlFor="overall-notes">Overall notes / service plan</label><textarea id="overall-notes" maxLength={8000} rows={5} value={doc.overallNotes} onChange={e=>manager.edit(d=>({...d,overallNotes:e.target.value}))} placeholder="Specialist commitments, follow-up appointment, ticket numbers, anything to remember…"/></div><p className="source-small">Your inspection is a personal record. Service commitments should also appear in Rivian’s written delivery or service record.</p></div></section>}
 {previous.length>0&&<details className="previous-checks"><summary>Previously recorded checks ({previous.reduce((n,s)=>n+s.items.length,0)})</summary><p className="source-small">Your earlier answers and notes are retained here. New area-based checks start separately where their scope changed, so an earlier partial check cannot mark an entire area as good. All recorded issues appear in Issues and every export.</p>{previous.map(s=><section key={s.id}><h3>{s.title}</h3><div className="item-list">{s.items.map(item=><CheckRow key={item.id} item={item} entry={doc.entries[item.id]} change={entry=>updateEntry(item.id,entry)}/>)}</div></section>)}</details>}
 <SourceNotes/>
 <footer className="bottom-bar"><div className="bottom-inner"><div className={'save-label '+(['error','offline','conflict'].includes(manager.saveState)?'error':'')} role="status">{manager.saveState==='saving'?<LoaderCircle size={16} className="compact-spinner"/>:manager.saveState==='saved'?<CloudCheck size={17}/>:<Clock3 size={17}/>}<span>{saveLabel}</span></div><div className="bottom-buttons"><button className="btn" onClick={async()=>{if(await manager.saveNow())toast.success('All changes saved to your account.');}} disabled={manager.saveState==='saving'||manager.saveState==='conflict'}><Save size={17}/>Save now</button><button className="btn primary" onClick={resetExport}><FileDown size={17}/>Export PDF</button></div></div></footer>
 </main>}
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="report-dialog" style={{maxWidth:680}}><DialogTitle>Vehicle details</DialogTitle><DialogDescription>Update your delivery details and configuration.</DialogDescription>{doc&&<MetaForm initial={doc.meta} editing busy={false} onCancel={()=>setEditing(false)} onSubmit={(meta,original)=>{manager.edit(d=>({...d,meta:{...d.meta,...Object.fromEntries(Object.entries(meta).filter(([key,value])=>value!==original?.[key as keyof VehicleMeta]))},accessoryNames:{...accessoryNamesFor(d.meta.accessories),...d.accessoryNames,...accessoryNamesFor(meta.accessories)}}));setEditing(false);toast.success('Vehicle details updated.')}}/>}</DialogContent></Dialog>
 <Dialog open={showExport} onOpenChange={setShowExport}><DialogContent className="report-dialog"><DialogTitle>Your inspection, on record.</DialogTitle><DialogDescription>Create a PDF of the current checklist. Exporting keeps your editable inspection available here.</DialogDescription>
 {!pdfUrl?<><Select value={pdfKind} onValueChange={setPdfKind}><SelectTrigger className="select-control" style={{width:'100%',minHeight:48,fontSize:16}} aria-label="PDF report type"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pickup">Pickup checklist — 20 core checks + accessories</SelectItem><SelectItem value="full">Complete record — pickup + follow-up</SelectItem><SelectItem value="issues">Issues only — for the specialist</SelectItem></SelectContent></Select><p className="small">Includes vehicle details, notes, agreed actions and all recorded issues. The complete record also includes follow-up and earlier saved checks. Your full VIN appears in the PDF.</p>{manager.saveState!=='saved'&&<div className="notice amber">This report will include your current edits and be marked as a draft until they are synced.</div>}<button className="btn primary full" onClick={()=>void exportPdf()} disabled={pdfBusy}>{pdfBusy?<LoaderCircle size={18} className="compact-spinner"/>:<FileDown size={18}/>} {pdfBusy?'Creating PDF…':'Create PDF'}</button></>:<div className="report-ready"><CheckCircle2 size={27} style={{marginBottom:12}}/><h3>Your PDF is ready.</h3><p className="small" style={{overflowWrap:'anywhere'}}>{pdfName}</p><div className="report-links"><button className="btn primary" onClick={()=>void sharePdf()}><Download size={17}/>Save / Share PDF</button><a className="btn" href={pdfUrl} download={pdfName}><FileDown size={17}/>Download PDF</a><a className="btn" href={pdfUrl} target="_blank" rel="noreferrer"><ExternalLink size={17}/>Open PDF</a></div><p className="source-small">On iPhone, choose Save to Files from the share sheet. The PDF is a snapshot; reopen this app to update the inspection.</p></div>}
 {pdfError&&<div className="error-box" role="alert">{pdfError}</div>}</DialogContent></Dialog>
 <Dialog open={manager.conflicts.length>0}><DialogContent className="report-dialog" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}><DialogTitle>Two devices edited this detail.</DialogTitle><DialogDescription>Other changes have been combined. Choose the value to keep for each conflict below.</DialogDescription>
 {manager.conflicts.map(conflict=>{const parts=conflict.path.split('.');const item=allItems.find(i=>i.id===parts[1]);const valueText=(value:unknown)=>parts.at(-1)==='status'?labels[String(value)]||String(value):typeof value==='boolean'?(value?'Yes':'No'):String(value)||'(empty)';return <div className="conflict-row" key={conflict.path}><h3>{item?.title||parts[1]||conflict.path} · {parts.at(-1)}</h3>{(['mine','theirs'] as const).map(choice=><label className="conflict-option" key={choice}><input type="radio" name={conflict.path} checked={conflictChoices[conflict.path]===choice} onChange={()=>setConflictChoices(c=>({...c,[conflict.path]:choice}))}/><span><strong>{choice==='mine'?'This device':'Saved on another device'}</strong>{valueText(conflict[choice])}</span></label>)}</div>})}
 <button className="btn primary full" disabled={manager.conflicts.some(c=>!conflictChoices[c.path])} onClick={()=>{manager.resolve(conflictChoices);setConflictChoices({})}}>Save selected values</button></DialogContent></Dialog>
 </>;
}
