'use client';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { type CheckItem, type Inspection, type Section, isReviewed } from '@/lib/model';
import { VehicleScene } from '@/components/vehicle-scene';
import { routeAngles, detailFor } from '@/lib/vehicle-views';
import { minutesLabel, sectionMinutes } from '@/lib/inspection-time';

const stops=['Front','Passenger side','Rear & cargo','Driver side','Cabin','Driver’s seat','Handover'];
function VehicleGuide({stop,item,angle}:{stop:number;item:CheckItem;angle:number}){
 return <div className="route-car"><div className="route-car-heading"><span>YOUR WALKAROUND</span><span>{stop+1} / 7</span></div><VehicleScene stop={stop} itemId={item.id} angle={detailFor(item.id)?routeAngles[stop]:angle} title={item.title}/><div className="route-current"><span className="route-dot"/><div><strong>{stops[stop]}</strong><p>{item.title}</p></div></div><p className="route-art-caption">Color shows the area to inspect · Rivian reference views</p></div>
}
export function InspectionWalkthrough({sections,doc,renderCheck,onReview}:{sections:Section[];doc:Inspection;renderCheck:(item:CheckItem)=>ReactNode;onReview:()=>void}){
 const root=useRef<HTMLDivElement>(null),guide=useRef<HTMLElement>(null);
 const [active,setActive]=useState({stop:0,id:sections[0].items[0].id,angle:66});
 useEffect(()=>{let raf=0;const update=()=>{raf=0;const cards=root.current?.querySelectorAll<HTMLElement>('[data-route-check]');if(!cards?.length)return;const mobile=window.innerWidth<=800;const line=mobile?Math.min((guide.current?.getBoundingClientRect().bottom||180)+36,window.innerHeight*.6):window.innerHeight*.34;let chosen=cards[0];for(const card of cards){if(card.getBoundingClientRect().top<=line)chosen=card;else break;}const id=chosen.dataset.routeCheck!;const stop=Number(chosen.dataset.routeStop);const next=Array.from(cards).find(card=>Number(card.dataset.routeStop)===stop+1);const distance=next?next.getBoundingClientRect().top-line:Infinity;const blend=Math.max(0,Math.min(1,1-distance/160));const angle=routeAngles[stop]+((routeAngles[stop+1]??routeAngles[stop])-routeAngles[stop])*blend;setActive(old=>old.id===id&&Math.abs(old.angle-angle)<.02?old:{id,stop,angle})};const schedule=()=>{if(!raf)raf=requestAnimationFrame(update)};window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);schedule();return()=>{window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);cancelAnimationFrame(raf)}},[sections]);
 const item=sections[active.stop]?.items.find(item=>item.id===active.id)||sections[0].items[0];
 return <div className="route-layout" ref={root}><aside className="route-guide" ref={guide}><VehicleGuide stop={active.stop} item={item} angle={active.angle}/><nav className="route-nav" aria-label="Walkaround stops">{sections.map((s,i)=><button key={s.id} aria-current={active.stop===i?'step':undefined} onClick={()=>document.getElementById('route-stop-'+s.id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><span>{i+1}</span>{stops[i]}<small>{s.items.filter(item=>isReviewed(doc.entries[item.id])).length}/{s.items.length}</small></button>)}</nav></aside><div className="route-checks"><p className="route-intro">One exterior lap → cabin → driver’s seat. Scroll to follow the route; the R2 turns with you.</p><div className="cycle-guide"><span>✓ 1 tap · Good</span><span>− 2 · Minor</span><span>× 3 · Major</span><span>4 · Reset</span></div>{sections.map((section,index)=><section className="route-stop" id={'route-stop-'+section.id} key={section.id}><div className="section-heading"><div><span className="section-number">STOP {index+1} / 7 · {minutesLabel(sectionMinutes[section.id])}</span><h2>{section.title}</h2><p>{section.subtitle}</p></div></div><div className="item-list">{section.items.map(item=>item.id.startsWith('accessory-')?null:<div key={item.id} data-route-check={item.id} data-route-stop={index} className={item.id==='quick-equipment'?'accessory-group':undefined}>{renderCheck(item)}{item.id==='quick-equipment'&&section.items.some(i=>i.id.startsWith('accessory-'))&&<div className="accessory-checks"><p className="accessory-checks-heading">Your ordered accessories · check each item</p>{section.items.filter(i=>i.id.startsWith('accessory-')).map(extra=><div key={extra.id} data-route-check={extra.id} data-route-stop={index}>{renderCheck(extra)}</div>)}</div>}</div>)}</div></section>)}<button className="btn primary full" onClick={onReview}>Review inspection →</button></div></div>
}
